### ISSUE TITLE
Reduce JDBC Lookups for Oracle

### ISSUE THREAD

**Issue by ryankwagner** [yahoo/maha#473]
Currently, JDBC lookups open a very large number of connections per node defined to make them, such that given an increasing number of nodes for query, the number of connections increases linearly.

This proposal is to create a new JDBC-based lookup type that offloads the inMemory data fetching into only a few LEADER nodes (3, for example) and delegates all other nodes into data reading (FOLLOWER).

Current architecture of JDBC Lookups:

1. Create a thread, on which a periodic Job is launched (once per minute, for example)
2. On that thread, scan a table for all data newer than current lastUpdated date.
3. For all data, save it by key->value pair into an in memory cache (JDBC)

New architecture of JDBC Lookups (Borrows Kafka writing logic from MissingLookupManager):

LEADER LOGIC
1. Create a thread, on which a periodic Job is launched (once per minute, for example)
2. On that thread, scan a table for all data newer than current lastUpdated date.
3. For all data, save it by key->value pair into a map
4. By the same logic as MissingLookupManager, populate a Kafka Topic (KafkaProducer using Protobuf) with the map contents.

FOLLOWER LOGIC
1. Create a thread, on which a KafkaConsumer is launched.
2. On that thread, constantly poll the above Kafka Topic on the assigned node pool for updates.
3. Use the same Protobuf as was used to populate the topic to read back into an in memory cache (JDBC).

**Comment by patelh** [comment]
Do you seed data to followers?  Or do they read everything from kafka topic?
If you have 3 leaders, do they all read the same table or different tables?

**Comment by ryankwagner** [comment]
We are having all leaders reading from the same tables.  This ensures redundancy in the Oracle -> Kafka component.
Each leader is a potential 'fallback' on writing to the current Kafka topic for each table.
The proposed action for writing Kafka topics representing the most current table data is only writing new data to the table's topic if its updated date is > the current topic's last updated date (timestamp as a flag).
Followers all spawn consumers for each topic.  One topic, one table.

**Comment by patelh** [comment]
If all leaders reading from the same tables, and write new entries to kafka topic, how do you deal with duplicates?

**Comment by ryankwagner** [comment]
In the case of all rows in the lookup using a unique cache key, is this duplication issue a concern?  By virtue of operating with a Map for the cache, dedupe should be automatically handled by the consumer.  If not, we could switch the Kafka Producer system to use the 0.11.x idempotency scheme.

**Comment by pavanab4u** [comment]
Duplication is not a concern. Kafka's idempotency will not solve this scenario because all the writers are standalone and independent of each other.

**Comment by patelh** [comment]
The duplication issue is only a concern for out of order updates due to multiple leaders potentially reading the data at different times.  You'll need to ensure updates from multiple leaders are applied only if the timestamp is same of updated.  Are the leaders fixed or are they elected at startup?

**Comment by pavanab4u** [comment]
Yes, updates should be applied if and only if timestamp >= current timestamp. To keep it simple, we should go with fixed leaders driven by configuration. Leader election can be a later enhancement.

**Comment by ryankwagner** [comment]
Currently working locally for full logic, local testing guide is in progress.
My setup is essentially:
MySQL (Through workbench 8.0)
Maha (current)
Kafka 2.12-2.2.0
Zookeeper 3.4.11
Druid 0.11.0

Load maha-druid-lookups zip through maven
Unzip and create maha-druid-lookups inside druid/extensions
Add kafka-clients copied from maha-druid-lookups into druid lib/ for Serializers (kafka has dependency-seeking issues)
Load the lookup as leader, should be able to cache MySQL updates
Load the lookup as follower, should be able to parse the Kafka topic.

TODOs:
- Leader election to support multi-node lookups.

**Comment by ryankwagner** [comment]
For configuration information on the connection to mySQL to use for local testing, use the configurations noted in the LocalTest strings for DriverManager getConnection String.
All ports used in testing (kafka, sql, etc) are the same as default values.

**Comment by ryankwagner** [comment]
This change is currently in Maha.  I am working on quickstart documentation to get this running locally, along with sample setup and two sample lookup tiers.  The requirement to get this running is that:
- A historical running Producer actions will run on a different tier than any running Consumer actions (so that multiple historicals can use distinct lookups).
- The local MySQL database with the table in use will be updated while the lookups are running.  This is because the first lookup instance uses default druid lookup behavior, subsequent loads switch to Producer/Consumer behavior.
- Be careful with the MySQL connection string!  If you're using the default mySQL setup, useSSL, etc. options need to be checked.
