### ISSUE TITLE
Support for a doubleSum aggregator in Druid

### ISSUE THREAD

**Issue by shravanak** [yahoo/maha#474]
Getting the following error when defining a Fact col that is a DecType
FactCol("revenue", DecType(10,8))

"errorMessage" : "Could not resolve type id 'roundingDoubleSum' into a subtype of [simple type, class org.apache.druid.query.aggregation.AggregatorFactory]: known type ids = [AggregatorFactory, HLLSketchBuild, HLLSketchMerge, approxHistogram, approxHistogramFold, arrayOfDoublesSketch, cardinality, count, doubleFirst, doubleLast, doubleMax, doubleMin, doubleSum, filtered, floatFirst, floatLast, floatMax, floatMin, floatSum, histogram, hyperUnique, javascript, longFirst, longLast, longMax, longMin, longSum, quantilesDoublesSketch, quantilesDoublesSketchMerge, sketchBuild, sketchMerge, stringFirst, stringFirstFold, stringLast, stringLastFold, thetaSketch]\n at [Source: HttpInputOverHTTP@23997a31[c=1080,q=0,[0]=null,s=STREAM]; line: 1, column: 692] (through reference chain: org.apache.druid.query.groupby.GroupByQuery[\"aggregations\"]->java.util.ArrayList[0])",

**Comment by pavanab4u** [comment]
@shravanak currently, RoundingDoubleSumAggregatorFactory is used for all DecType. 'roundingDoubleSum' is a module added by us which is not part of standard Druid module. We will have make DruidQueryGenerator to use either RoundingDoubleSumAggregatorFactory or just DoubleSumAggregatorFactory based on configuration. 
Do you want to make this change? Code is here https://github.com/yahoo/maha/blob/master/core/src/main/scala/com/yahoo/maha/core/query/druid/DruidQueryGenerator.scala#L845

**Comment by pranavbhole** [comment]
fixed long back, configurable params at the DruidQuery Generator now.
