### ISSUE TITLE
Plans to support newer druid versions for maha-lookups?

### ISSUE THREAD

**Issue by swapneshgandhi** [yahoo/maha#625]
Hi,
We are exploring using maha-lookups in our Druid cluster.
Just noticed that per the docs, only druid 0.11 is supported at the moment. Are there any plans to support newer druid versions?

**Comment by pavanab4u** [comment]
@swapneshgandhi , yes we are in the process of supporting up until the latest version of druid, maybe in a month. what version of druid are you using?

**Comment by swapneshgandhi** [comment]
We are on Druid 0.15

**Comment by swapneshgandhi** [comment]
Couple more questions:
In the maha-lookup section: it says 'The default behavior for RocksDB is to grab a snapshot from HDFS daily and apply updates from Kafka from beginning of topic retention period.'

I am unsure how hdfs and kafka are interacting here. If Rocks DB is reading from HDFS daily, are the kafka updates only relevant during the day?
Or Rocks DB is getting one time snapshot from hdfs and all updates are managed through Kafka?

How confident are you of supporting newer Druid versions in few months? Asking because we'd like to use this extension but want to be sure its something we can do. Is there any PR i can follow for the progress?


thanks!

**Comment by pavanab4u** [comment]
RocksDB gets the daily snapshot from HDFS and applies updates from Kafka from begging of the topic retention period - This is done to make sure realtime dimension updates are applied to the snapshot downloaded by historicals. It assumes that HDFS snapshot will not be latest, more realtime will always be available through Kafka. This whole process is done everyday to make sure that RocksDB doesn't grow in size with unwanted/inactive entries. You would create daily HDFS snapshot with only relevant entries.

How confident are you of supporting newer Druid versions in few months?
We are confident as we have to upgrade our Druid cluster to latest version in a month. @sapphirew has started working on this. He'll tag you in the PR that he is going to create soon.

**Comment by swapneshgandhi** [comment]
thanks for the information @pavanab4u.
I am thinking a bit about how are pipeline would look like if we were to adopt this.
Currently we store our lookups in HDFS and MySQL. Druid loads them from MySQL

Would rocksdb pull daily snapshots from HDFS to each historical/broker node? or how does that work? Is the snapshot then stored on local ssd?
Is Druid using an in-memory rocks db?
Sorry, I am not familiar with rocks db, so I feel like I am missing something.

What about the serialization? Do we need these snapshots to be in Protobuf format?

thanks!

**Comment by pranavbhole** [comment]
@swapneshgandhi  snapshots are rocksb instance zip. Yes, as of now you need protobuf to SerDe values in the rocksdb. I am working on adding Flat Buffer as another SerDe. If you plan to use other SerDe then you can extend it too.

**Comment by patelh** [comment]
@swapneshgandhi just to clarify, here is what you would need to do to use the rocksdb lookups.

Assumptions:
1. You have some dimension dataset on HDFS in a readable format from a Java application(e.g. CSV, TSV, or some delimited format).
2. The dataset is snapshot of all dimension data at some interval.  E.g. daily snapshot.  Each how has the last updated timestamp column.
3. You have a Kafka topic with a TTL at slightly larger then the snapshot interval.  E.g. snapshot is every 24 hours, the Kafka topic retains messages for 26 hours.
3. You have updates to the dimensions which you can publish to a kafka topic in the same key/value format you create the rocksdb instance (see below) with a valid last updated timestamp from your source of truth system.

Steps:
1. Define your protobuf message format.  Remember to include the last updated timestamp column.  Create a jar library which has the java protobuf definitions so you can copy it to the druid historical nodes and put it in the druid libs folder.
2. Create a application which reads your dataset from HDFS and creates a rocksdb instance and inserts all the rows into the rocksdb instance in the same format as you expect to read it in maha druid lookups.  E.g. the key would just be the String.getBytes() and the value would be the serialized protobuf bytes. Once all rows are inserted close the rocksDb instance, zip it up and upload it to HDFS path.
3. Schedule your application to run every day after your dimension snapshots are available.
4. Configure maha druid lookup extension on your historicals.
5. Register your lookup via the API

I am sure I am missing steps, @pavanab4u can you fill in the gaps.  I forgot how the audit and missing lookups functionality works.  Audit as the name implies is for auditing the lookups are valid. The missing lookups config is a way to publish the missing keys to a topic so another process can listen to missing keys and attempt to publish them to the kafka topic the historicals are already listening to.

@pavanab4u @pranavbhole we really should document this if we already haven't.
