### ISSUE TITLE
Druid filter on facts not included in the list of request columns

### ISSUE THREAD

**Issue by ishan8** [yahoo/maha#634]
We have a Druid query use case where we want to filter out rows where an aggregated metric is less than a specified threshold, but don't want that metric's column included in the list of output columns.

This is possible with dimension columns but not with fact columns. Only fact columns in the list of request columns are added to the list of fact aggregators.
```
    val factCols = queryContext.factBestCandidate.factColMapping.toList.collect {
      case (nonFkCol, alias) if queryContext.factBestCandidate.requestCols(nonFkCol) =>
        (fact.columnsByNameMap(nonFkCol), alias)
    }
```
https://github.com/yahoo/maha/blob/master/core/src/main/scala/com/yahoo/maha/core/query/druid/DruidQueryGenerator.scala#L1143

Trying to understand why we need the `queryContext.factBestCandidate.requestCols(nonFkCol)` check. Would there be any issues if we removed it in order to support filtering on non output fact columns?

**Comment by patelh** [comment]
Trying to understand the use case, e.g. you want to exclude rows with clicks < 5, but you are saying you don't want to include the click count in output, just for filtering rows right?  Best way to show what you are trying to do is create a PR with a broken test case.

**Comment by ishan8** [comment]
Yes, as you said in the example you're describing, we'd just want to exclude rows with clicks < 5, but not display the click count.

A query like this would currently generate no aggregations on the clicks column because it's not included in `selectFields` list, so the `having` clause generated for the filter on the aggregated fact wouldn't work either.
```
{
  "cube": "k_stats",
  "selectFields": [
    {"field": "Advertiser ID"},
    {"field": "Country"},
    {"field": "Revenue"},
  ],
  "filterExpressions": [
    {"field": "Day", "operator": "=", "value": "$fromDate"},
    {"field": "Advertiser ID", "operator": "=", "value": "12345"},
    {"field": "Clicks", "operator": ">", "value": "5"}
  ],
  "paginationStartIndex":20,
  "rowsPerPage":100
}
```
I can create a PR with a broken test case if you think it would help.

**Comment by patelh** [comment]
Feel create to create a PR with your test case and the change you proposed above.
