### ISSUE TITLE
Combining data from datasources based on date range

### ISSUE THREAD

**Issue by swapneshgandhi** [yahoo/maha#757]
Hi all,
I have a usecase where we'd like to combine data from separate datasources based on the timerange of the query.
We have a datasource with realtime data( latest 24 hrs) and separate one with historical data(older than 24 hrs). 

Is it possible to setup this in a way that if a query comes in for last 14 days, Maha would query realtime data for latest day and historical data for rest of the time range and then combine those results??

Similarly along that line, the decision to choose the preferred dataset could be based on 'data availability' and not just on strict date ranges.

**Comment by swapneshgandhi** [comment]
Actually we found another way around that does not need Maha.
so closing this.

**Comment by patelh** [comment]
@swapneshgandhi You could have done it with maha by writing your own curator that does what you described.  Curators are essentially taking an incoming request and curating it to specific business logic.  You can look at existing curator code for examples.  It's designed so anyone can write their own curators and inject them in the config and use them as they want, no need to open source them if it's specific to your use case.
