### ISSUE TITLE
Ability to set different Druid URLs per table to support Broker Tiering

### ISSUE THREAD

**Issue by ryankwagner** [yahoo/maha#983]
Add an additional parameter similar to group by strategy called "url" which can override the executor config.

https://github.com/yahoo/maha/blob/master/druid/src/main/scala/com/yahoo/maha/executor/druid/DruidQueryExecutor.scala#L451

**Comment by ryankwagner** [comment]
The specific line to use for Fact inspection is here:
https://github.com/yahoo/maha/blob/master/druid/src/main/scala/com/yahoo/maha/executor/druid/DruidQueryExecutor.scala#L447

To ensure the param may be used.

**Comment by pranavbhole** [comment]
looks good.

**Comment by ryankwagner** [comment]
Associated PR:
https://github.com/yahoo/maha/pull/984
